nix --extra-experimental-features nix-command eval -f ./testrunner.nix res1a
nix --extra-experimental-features nix-command eval -f ./testrunner.nix res1b
nix --extra-experimental-features nix-command eval -f ./testrunner.nix res2
nix --extra-experimental-features nix-command eval -f ./testrunner.nix res3
nix --extra-experimental-features nix-command eval -f ./testrunner.nix res4a
nix --extra-experimental-features nix-command eval -f ./testrunner.nix res4b
nix --extra-experimental-features nix-command eval -f ./testrunner.nix res4c
nix --extra-experimental-features nix-command eval -f ./testrunner.nix res5
nix --extra-experimental-features nix-command eval -f ./testrunner.nix res6
